name: nippo
description: This is a daily report app, and it's a sample app using Flutter and Firebase.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '^3.0.0'

dependencies:
  adaptive_dialog: ^1.10.0
  adaptive_theme: ^3.4.1
  cached_network_image: ^3.3.0
  cloud_firestore: ^5.4.2
  cupertino_icons: ^1.0.6
  # 未マージのためgit指定
  # ref. https://github.com/invertase/flutter_desktop_webview_auth/pull/51
  desktop_webview_auth:
    git: https://github.com/andyshephard/flutter_desktop_webview_auth
  firebase_app_check: ^0.3.1+2
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^12.1.1
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.4.6
  intersperse: ^2.0.0
  intl: ^0.19.0
  json_converter_helper: ^0.1.2
  provider: ^6.1.1
  recase: ^4.1.0
  riverpod_annotation: ^2.3.1
  simple_logger: ^1.9.0+3
  smooth_highlight: ^0.1.1
  tsuruo_kit: ^0.2.1
  url_launcher: ^6.2.1
  version: ^3.0.2

dev_dependencies:
  analyzer: ^5.13.0
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2
  freezed: ^2.4.5
  go_router_builder: ^2.3.4
  json_serializable: ^6.7.1
  melos: ^3.2.0
  pedantic_mono: ^1.24.0
  riverpod_generator: ^2.2.4
  riverpod_lint: ^2.1.1

dependency_overrides:
  # melosが `http ^0.13.1`に依存しているが`dev_dependencies`でユーザー影響が無いためoverridesする
  # google_fonts ^5.0.0 and melos ^3.1.0
  http: ^1.0.0
  win32: ^5.0.9

flutter_icons:
  android: true
  ios: true
  image_path: assets/image/appicon.png

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/
