// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzI4tTE_4Rjd-1kSI9A_1_hkR9YKD-i18',
    appId: '1:85091586156:web:db6115fd0acbe8b6370849',
    messagingSenderId: '85091586156',
    projectId: 'practice-nippo',
    authDomain: 'practice-nippo.firebaseapp.com',
    storageBucket: 'practice-nippo.appspot.com',
    measurementId: 'G-CEWBNHG6M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJN6uIvo0EaMtSFRkCah8fzq8c0r3p8_4',
    appId: '1:85091586156:android:399799181f576eb1370849',
    messagingSenderId: '85091586156',
    projectId: 'practice-nippo',
    storageBucket: 'practice-nippo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp4ynGeuaKbHLcKbLmuigkGpwC3WuWfy0',
    appId: '1:85091586156:ios:69f9da8a852190a6370849',
    messagingSenderId: '85091586156',
    projectId: 'practice-nippo',
    storageBucket: 'practice-nippo.appspot.com',
    iosBundleId: 'com.htsuruo.nippo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp4ynGeuaKbHLcKbLmuigkGpwC3WuWfy0',
    appId: '1:85091586156:ios:69f9da8a852190a6370849',
    messagingSenderId: '85091586156',
    projectId: 'practice-nippo',
    storageBucket: 'practice-nippo.appspot.com',
    iosBundleId: 'com.htsuruo.nippo',
  );

}